basePath: /api/v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  user.AuthResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/user.EUser'
    type: object
  user.EUser:
    properties:
      account_id:
        type: integer
      balance:
        type: number
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        type: string
      updatedAt:
        type: string
    type: object
  user.UserDTO:
    properties:
      account_id:
        type: integer
      balance:
        type: number
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple API server for user management and transactions.
  title: Simple Api
  version: "1.0"
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Create a new user account profile in the system
      parameters:
      - description: User Registration Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.AuthResponse'
        "400":
          description: Invalid input data
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Auth
swagger: "2.0"
